name: Build and Deploy Spring Boot App

on:
  push:
    branches:
      - main  # Adjust if your default branch is different

jobs:
  setup-postgres:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install PostgreSQL if not installed
        run: |
          if ! command -v psql > /dev/null; then
            sudo apt-get update
            sudo apt-get install -y postgresql postgresql-contrib
          fi

      - name: Ensure PostgreSQL is running
        run: |
          sudo systemctl start postgresql
          sudo systemctl enable postgresql

      - name: Setup PostgreSQL Database and User
        run: |
          sudo -u postgres psql -tc "SELECT 1 FROM pg_database WHERE datname = 'handihub'" | grep -q 1 || sudo -u postgres psql -c "CREATE DATABASE handihub"
          sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'root'"

  build:
    runs-on: ubuntu-latest
    needs: setup-postgres

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install PostgreSQL
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql postgresql-contrib
          sudo systemctl start postgresql
          sudo systemctl enable postgresql
          sudo -u postgres psql -tc "SELECT 1 FROM pg_database WHERE datname = 'handihub'" | grep -q 1 || sudo -u postgres psql -c "CREATE DATABASE handihub"
          sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'root'"

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: ./gradlew build

      - name: Copy jar file to server
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: build/libs/*.jar
          target: /home/${{ secrets.SERVER_USER }}/app.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Delete previous jar file if exists
        run: |
          if [ -f /home/${{ secrets.SERVER_USER }}/app.jar ]; then
            echo "Removing old app.jar file..."
            rm -f /home/${{ secrets.SERVER_USER }}/app.jar
          fi

      - name: Clean up old files
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh ${ secrets.SERVER_USER }@${{ secrets.SERVER_HOST }} "find /home/${{ secrets.SERVER_USER }}/ -name '*.jar' -type f -delete"

      - name: SSH to Server and Run Jar
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            echo "Stopping any running app.jar process..."
            pkill -f 'java -jar app.jar' || true
            echo "Starting new app.jar process..."
            nohup java -jar /home/${{ secrets.SERVER_USER }}/app.jar > /home/${{ secrets.SERVER_USER }}/app.log 2>&1 &
            echo "Deployment complete."
  
